# import = ["/home/dane/.config/alacritty/melange.yml"]

[font]
size = 12

[font.normal]
family = "JetBrainsMonoNL Nerd Font"
style = "Regular"

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "none"
opacity = 0.9

# Melange
[colors.primary]
foreground = '#ECE1D7'
background = '#292522'

[colors.normal]
black =   '#34302C'
red =     '#BD8183'
green =   '#78997A'
yellow =  '#E49B5D'
blue =    '#7F91B2'
magenta = '#B380B0'
cyan =    '#7B9695'
white =   '#C1A78E'

[colors.bright]
black =   '#867462'
red =     '#D47766'
green =   '#85B695'
yellow =  '#EBC06D'
blue =    '#A3A9CE'
magenta = '#CF9BC2'
cyan =    '#89B3B6'
white =   '#ECE1D7'
